# Generated by Django 4.1.4 on 2022-12-23 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('body', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата релиза')),
                ('boolean', models.BooleanField(verbose_name='Доступность')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.rubric')),
            ],
            options={
                'verbose_name': 'Смартфон',
                'verbose_name_plural': 'Смартфоны',
                'ordering': ('-date',),
            },
        ),
    ]
