# Generated by Django 4.1.4 on 2022-12-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
